dist: trusty
sudo: false
git:
  depth: false
addons:
  sonarcloud:
    organization: lucacappelletti94-github
    token:
      secure: NCmKpaZFv4yYP7n8zBeHQc6tyzKYNmGlbr1OJKkUSrcuEh1HNI6HxTFXtrNJfTUolgm0OwZDAGLhWPKDWKI1yy9d4hRK9A3cGoKL1Bfy25Gd/Xjxhn9zkedvhOAAETrxEG7+YuOFS2TaIzV9qqPKnU8BfjYrLU2EYoGq7izISBRE35djFfqgmd+qkjCRZ8iHmyArm17H8ViQUjgPRa67L48Zb9nzjdWDD3NzHsCK5Myc7sEMUyRpya1Or01CjqAoXe3fYR406POS265tTIh1gKusA2bvwDV9oHZnWxSoRdr1G5Y0eHVSRCCjWfOSfNHS+UULl0Ay2eV4A2VgkNKeGRMLAzDUFM5YI1xnHcI72hQdPqaMexmGGanp6tx36Diy0sVSrlIBeAmKzIJPatsbauDYWZrwzhpfHdz22+wnwwLTv8BUFeT36y8lMq2b/nC7dwjA81/t3JI1EC7kkDMzwRLeyLUiEojnVgMm5Kdmma8YzqcHdWRjCNLwM/9mRrgApshxzvP50ftcyXG2WYj2T9C/4zvfHb3AEuiOto5iWtZZtRrg85UBlHcNTGWwTRInol1eC4jHvrZ/Erp8NTd8DRrxMrzAA/mRllA0Gz7d9lTXY1w7r+Wf+vMW5fY3nzAE5qB6BvaZ3rki1/WAYNayX3J85KS9CcAmUpi2zleJuWY=
language: python
python:
- '3.6'
before_install:
- pip install --upgrade pytest
install:
- pip install .[test]
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=keras_synthetic_genome_sequence --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi
after_success:
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: dL9gzlM/4f+3hnQVhhHdhso2wlr3JZOa7hjxhZmBnEQrj/GNHsOymGa9Rrhv43yfmnFPRvU30ffgEZkvEOcbEwZt6s9PwIR19XCAN4YXon9ys+VN1wnA/xjkdGyPn0vG1np+70ZKztEiRyqMKRxx6vw8ll/2GjrklZs8QL+iWXTkMcpFkBB5fdUTiWED7Q3Ml2+hgXvmN9UVXGc2PLiQCWUR3hNMyjVSPLD3OWny5XZu1M/EOYwjfRR+OuB/ktDlUGUobD31D145W+UMcwAoFazTtcxab2CgmMWsCH3IvDMcsHUiuayLlfy3MPTAcQJZlCdBLl5kvx2D5oxEZvZ6S7mCboXW73ljkNSwjNRUmG2iV6HtyeS59yR1g/MjM6S33elXAWVnR+Xy80k4vLGjCcWfi+sLlzhhzQ1UehQnYuY6L9YEjyRuqARJR8NlDD2K0gfTgG0+3Jnfzvim+LCEl6zkKpiz992CAJJTd/5T1vV/hUKeV55zhboW4tBBp9RboPygE8OKncKoqRF7aj0gFo81nTufbVzFrkTbyXLugZWWIx24LNauGaWIx1OQzypIHnxNMga4gzy8x7AYeLsN2ZcmiOqy0fEERKIQOYETKSepDpCCKAtAP6bmUZTO9E5kKoQ45RO00b0+FE/0yA2NMbBDIL82gRx5FcOdZu6ZoHQ=
  - secure: fyDFkWr7kUv97Dh9PK9Vafy5bZsi64GrBQWv2tnP8W6Qqy/G8DQ8NCTNx0N0qkDDUuoKgXlUfd/mzsuQ61C8lPYfSHoQ+fx7lBFE+gBy51eGsszA0w0SDSFCh4oZr02roC3I+FsFUK5rlFu3/ggpJMovdgNfSFhWv3NkXv5rhgKfHQZM66QrmEVNazzW18wRihUZA+SgdNQVIG86PttTyau56AMKiyr4PiGbSV1mRXVB4em0ArxESkvKqdPcFec8TSZ6KLjoqZ7ulMNXQNupHiPhwY6OtBE172aPejtjSTCSQ/I3NZX0qEl/4GkSmdDUB0q/3hAS3FBKIt/dfP99SWoG6AyEDdxQZkkIaYloiuOWkfxq7alVXLF0LUoAqwusJep4xbP0OjX/RllwWWiJYhF3jENDQ3aai36+8Penrj2fulN7041U8UhG+SkjZcZSnZh0XOh7+iPs2ypSoOuaBodx/QYHy772/Rfc0za4LHS7h1QDXIxE+74udZHlwxfW5ZN7wo2oSxOnLwDZAnY5bIaMK3ge2RK4B3RDc28NCxuzrtZGvOOoqFXUiRElQddZz2jKyW82Vux9FW9Ns5I03orDjIoqK5tsMyjgLd6p9mTvXbMULDYI6XL7R/RwmpZ9DU03pHW4D/Ngj6sn20+cqU1+WBPy/WNWruDdWZT+kj8=
